services:
  web:
    build: .
    ports:
      - "8080:80"

  db:
    build: web/sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vide_grenier
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

